version: "2"

services:
        fulfiller:
                build: orderFulfiller
                networks:
                        - messagingShow
                ports:
                        - "8081:8081"
        customer:
                build: customer
                networks:
                        - messagingShow
                ports:
                        - "8082:8082"

networks:
        messagingShow:
